sudo: false
language: node_js
node_js:
- '6.0'
cache:
  directories:
  - node_modules
branches:
  only:
  - main
notifications:
  email: false
before_script:
- cd metacurious; npm install
script:
- npm run --silent build
after_success:
- bash ../deploy.sh
env:
  global:
  - GH_USER: neurostuff
  - GH_REPO: metaCurious
  - secure: ???
